baseURL = 'https://blog.wanye7300.xyz/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
title = "Wanye_7300's Site"
theme = 'hugo-theme-stack'

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[params]
  favicon = 'img/icon_small.png'

  [[params.widgets.homepage]]
  type = 'home'

  [[params.widgets.homepage]]
  type = 'search'

  [[params.widgets.homepage]]
  type = 'archives'
    [params.widgets.homepage.params]
    limit = 5
  
  [[params.widgets.homepage]]
  type = 'categories'
    [params.widgets.homepage.params]
    limit = 10
  
  [[params.widgets.homepage]]
  type = 'tag-cloud'
    [params.widgets.homepage.params]
    limit = 10
  
  [[params.widgets.page]]
  type = 'toc'

  [params.footer]
  since = 2025
  customText = 'Learn from the past, live for today and hope for the <em>future</em>.'

  [params.sidebar]
  emoji = '🍺'
  subtitle = 'W A N Y E 7 3 0 0'
    [params.sidebar.avatar]
    src = 'img/icon_small.png'
  
  [params.article]
  headingAnchor = false
  math = true
  toc = true
  readingTime = true
    [params.article.license]
    enabled = true
    default = 'Licensed under CC BY-NC-SA 4.0'
  
  [params.comments]
  enabled = true
  provider = 'waline'
    [param.comments.waline]
    serverURL = 'https://blog-comment.wanye7300.xyz/'
    lang = 'zh-CN'
    emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
    requiredMeta = ['nick', 'mail']
      [param.comments.waline.locale]
      admin = 'Wanye_7300'

[menu]
  [[menu.main]]
    name = '主页'
    url = '/'
    weight = -2147483648
    identifier = 'home'
    [menu.main.params]
        icon = 'home'
        newTab = false
  [[menu.social]]
  identifier = 'github'
  name = 'Github'
  url = 'https://github.com/Wanye-7300/'
  [menu.social.params]
  icon = 'brand-github'
  newtab = true
